# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Anticipatory Power Flow
author: ""
copyright: "2022 - present, Christian Cahig"
only_build_toc_files: true

execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true

latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: primer.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/christian-cahig/apf-primer
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: true
  home_page_in_navbar: false
  extra_navbar: <i>Powered by <a href="https://jupyterbook.org">Jupyter Book</a></i>
  extra_footer: This document is licensed under the Creative Commons Attribution 4.0 International Public License.

sphinx:
  config:
    html_show_copyright: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
